language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - 2.0.0
  - rbx-18mode
  - rbx-19mode
  - ruby-head


script: "bundle exec rake travis"

notifications:
  email:
    on_success: always

before_install: "sudo gem update --system"

