language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head


script: "bundle exec rake travis"

notifications:
  email:
    on_success: always
matrix:
  allow_failures:
    - rvm: 1.9.2
    - rvm: 1.8.7
    - rvm: ruby-head
