language: ruby
before_install:
  - gem update bundler
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.3
  - 2.3.0
  - ruby-head


script: "bundle exec rake test:unit:all"

notifications:
  email:
    on_success: always
matrix:
  allow_failures:
    - rvm: ruby-head
