begin
  require 'rake'
rescue LoadError
   require 'rubygems'
   require 'rake'
 end

 # we can require 'rake/clean' to add 'clobber' and 'clean' tasks
 require 'rake/clean'



 SRC = FileList['**/*.rb']

 CLOBBER.include('doc', '**/*.html', '**/*.gem')

 # testing
 require 'rake/testtask'
 Rake::TestTask.new do |t|
   t.test_files = FileList.new('test/**/*.rb').to_a
 end

 # Build the gem package
 #load 'yanser.gemspec'
 #require 'rubygems/package_task'
 #Gem::PackageTask.new(GEMSPEC).define

 # Generate documentation
 require 'rdoc/task'
 RDoc::Task.new do |rdoc|
   rdoc.rdoc_files.include('lib/**/*')
 end
