#!/bin/sh

# For the purpose of SHALMANESER, disable the normal TreeTagger tokenisation
# Set these paths appropriately

command -v realpath >/dev/null 2>&1 || {
    echo >&2 "I require <realpath> but it's not installed.  Aborting."
    exit 1
}

BASE_DIR=$(dirname $(realpath $0))

#BASE_DIR=/home/arbox/work_space/shalm/dev/program_de/tools/treetagger

BIN=${BASE_DIR}/bin
CMD=${BASE_DIR}/cmd
LIB=${BASE_DIR}/lib

TOKENIZER=${BIN}/separate-punctuation
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/english-abbreviations
PARFILE=${LIB}/english.par

# put all on one line
cat $* |
# do tokenization
#$TOKENIZER +1 +s +l $ABBR_LIST |
# separate clitics from preceding words
#sed -e "s/'s"'$'"/ 's/g" \
#-e "s/s'"'$'"/ '/g" \
#-e "s/n't"'$'"/ n't/g" \
#-e "s/'re"'$'"/ 're/g" \
#-e "s/'ve"'$'"/ 've/g" \
#-e "s/'d"'$'"/ 'd/g" \
#-e "s/'m"'$'"/ 'm/g" \
#-e "s/'em"'$'"/ 'em/g" \
#-e "s/'ll"'$'"/ 'll/g" \
#-e '/^$/d' |
#tr ' ' '\n' |
# remove empty lines
#grep -v '^$' |
# tagging
$TAGGER $PARFILE -token -lemma -sgml 

