#!/bin/sh

# For the purpose of SHALMANESER, disable the normal TreeTagger tokenisation

# Set these paths appropriately


command -v realpath >/dev/null 2>&1 || {
    echo >&2 "I require <realpath> but it's not installed.  Aborting."
    exit 1
}

BASE_DIR=$(dirname $(realpath $0))

#BASE_DIR=/home/arbox/work_space/shalm/dev/program_de/tools/treetagger

BIN=${BASE_DIR}/bin
CMD=${BASE_DIR}/cmd
LIB=${BASE_DIR}/lib

TOKENIZER=${BIN}/separate-punctuation
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/german-abbreviations
PARFILE=${LIB}/german.par
FILTER=${CMD}/filter-german-tags

# put all on one line
cat $* |
# do tokenization
#$TOKENIZER +1 +s +l $ABBR_LIST |
# remove empty lines
grep -v '^$' |
# tagging
$TAGGER -token -lemma -sgml $PARFILE  | 
# error correction
$FILTER

